language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
- julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("FixedFeccts"); Pkg.test("FixedFeccts"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("FixedFeccts")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
